### ISSUE TITLE
Acmesolver container has runAsNonRoot and image has non-numeric user (nobody)

### ISSUE THREAD

**Issue by lonyai** [openshift/jetstack-cert-manager#18]
I intalled the cert-manager to the Openshift 4.15, and try to issue the first certification, but the challenge's pod couldn't start.

I found the issue for this command:

oc get pods -n openshift-config cm-acme-http-solver-XXX -o yaml
...
  containerStatuses:
  - image: registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:32cd645f60a8f59673639ee4b7828e8eb703eef2c4409ea95b93d41f24329d83
    imageID: ""
    lastState: {}
    name: acmesolver
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'container has runAsNonRoot and image has non-numeric user (nobody),
          cannot verify user is non-root (pod: "cm-acme-http-solver-khrd7_openshift-config(4a3aa11e-f79c-4fcc-a2fc-b0bd47b65ec6)",
          container: acmesolver)'
        reason: CreateContainerConfigError

I see in the line 19 of the cert-manager/jetstack-cert-manager-acmesolver-rhel9 's Dockerfile, the user is nobody:
https://catalog.redhat.com/software/containers/cert-manager/jetstack-cert-manager-acmesolver-rhel9/643959393e1850c127e4f3e5?architecture=amd64&image=659c4826128b8fc1244158c0&container-tabs=dockerfile

/kind bug

**Comment by swghosh** [comment]
Are you running this pod in the `default` namespace, by any chance?

**Comment by lonyai** [comment]
It was in the openshift-config namespace. I got a strange answer from the Red Hat. The http method is not supported in this namespace, and I have to use a dns method.

**Comment by swghosh** [comment]
This is being tracked at [OCPBUGS-33282](https://issues.redhat.com/browse/OCPBUGS-33282).
